# Generated by Django 4.2.23 on 2025-09-05 00:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0002_alter_note_author_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClaimDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mrn', models.CharField(blank=True, max_length=64)),
                ('facility', models.CharField(blank=True, max_length=128)),
                ('provider_name', models.CharField(blank=True, max_length=128)),
                ('provider_npi', models.CharField(blank=True, max_length=32)),
                ('admission_date', models.DateField(blank=True, null=True)),
                ('primary_diagnosis', models.CharField(blank=True, max_length=32)),
                ('icd10_codes', models.JSONField(blank=True, default=list)),
                ('drg', models.CharField(blank=True, max_length=16)),
                ('place_of_service', models.CharField(blank=True, max_length=32)),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('claim', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detail', to='claims.claim')),
            ],
        ),
    ]
