# Generated by Django 4.2.23 on 2025-09-05 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0003_claimdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='detail_info',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.DeleteModel(
            name='ClaimDetail',
        ),
    ]
