# Generated by Django 4.2.23 on 2025-09-09 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0004_claim_detail_info_delete_claimdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='need_review',
            field=models.BooleanField(default=False),
        ),
    ]
